path:
  data_path: '/home/proto/study/OilSpill-SSL/data'
  out_path: '/home/proto/study/OilSpill-SSL/result'

params:
  seed : 42
  sup_epochs: 300
  ssl_epochs: 300
  batch_size: 16
  learning_rate: 0.0001

model:
  name: 'UNet'  # 'UNet', 'DeepLabV3plus'
  encoder_name: 'resnet101' # 'resnet50', 'resnet101'